# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  win: circleci/windows@2.2.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build-exec:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    # docker:
    #   - image: adambusch/per_firmware:latest
    #resource_class: windows.medium
    executor:
      name: win/default
      shell: powershell.exe
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run: systeminfo
      - run:
          command: echo hello
      - run:
          command: ls
      - run:
          command: "python -m pip install -r requirements.txt"
      - run:
          name: "Prepare Libraries"
          command: "python -m pip install pyinstaller"
      - run:
          name: "Build"
          command: "python -m PyInstaller --onefile ./main.spec"
      - run:
          name: "Prepare Artifacts"
          command: |
            mkdir artifacts
            cp "./dist"/*.exe" artifacts
      - store_artifacts:
          path: artifacts

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build-workflow:
    jobs:
      - build-exec
