# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui\carView.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_carViewer(object):
    def setupUi(self, carViewer):
        carViewer.setObjectName("carViewer")
        carViewer.resize(879, 288)
        self.verticalLayout = QtWidgets.QVBoxLayout(carViewer)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(carViewer)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_11 = CANVariableDisplay(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_3.addWidget(self.label_11)
        self.label_14 = CANVariableDisplay(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_3.addWidget(self.label_14)
        self.label_15 = CANVariableDisplay(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_3.addWidget(self.label_15)
        self.label_16 = CANVariableDisplay(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_3.addWidget(self.label_16)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.verticalLayout.addWidget(self.groupBox_3)

        self.retranslateUi(carViewer)
        QtCore.QMetaObject.connectSlotsByName(carViewer)

    def retranslateUi(self, carViewer):
        _translate = QtCore.QCoreApplication.translate
        carViewer.setWindowTitle(_translate("carViewer", "Form"))
        self.groupBox_3.setTitle(_translate("carViewer", "Precharge Status"))
        self.label_11.setText(_translate("carViewer", "Main_Module.precharge_state.precharge_complete"))
        self.label_14.setText(_translate("carViewer", "Main_Module.precharge_state.precharge_error"))
        self.label_15.setText(_translate("carViewer", "Main_Module.precharge_state.v_mc"))
        self.label_16.setText(_translate("carViewer", "Main_Module.precharge_state.v_bat"))
from display_widgets.variables.can_variable_display import CANVariableDisplay
