# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui\connectionErrorDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConnectionErrorDialog(object):
    def setupUi(self, ConnectionErrorDialog):
        ConnectionErrorDialog.setObjectName("ConnectionErrorDialog")
        ConnectionErrorDialog.resize(400, 269)
        self.verticalLayout = QtWidgets.QVBoxLayout(ConnectionErrorDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(ConnectionErrorDialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.addressText = QtWidgets.QLineEdit(ConnectionErrorDialog)
        self.addressText.setObjectName("addressText")
        self.verticalLayout.addWidget(self.addressText)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.retryButton = QtWidgets.QPushButton(ConnectionErrorDialog)
        self.retryButton.setObjectName("retryButton")
        self.horizontalLayout.addWidget(self.retryButton)
        self.cancelButton = QtWidgets.QPushButton(ConnectionErrorDialog)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(ConnectionErrorDialog)
        QtCore.QMetaObject.connectSlotsByName(ConnectionErrorDialog)

    def retranslateUi(self, ConnectionErrorDialog):
        _translate = QtCore.QCoreApplication.translate
        ConnectionErrorDialog.setWindowTitle(_translate("ConnectionErrorDialog", "Connection Error"))
        self.label.setText(_translate("ConnectionErrorDialog", "Connection failed. Enter an ip address of the server if using wireless mode. Otherwise, check the usb connection."))
        self.retryButton.setText(_translate("ConnectionErrorDialog", "Retry"))
        self.cancelButton.setText(_translate("ConnectionErrorDialog", "Cancel"))
