# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui\fileViewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_fileViewer(object):
    def setupUi(self, fileViewer):
        fileViewer.setObjectName("fileViewer")
        fileViewer.resize(400, 366)
        self.verticalLayout = QtWidgets.QVBoxLayout(fileViewer)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(fileViewer)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.nodeSelector = QtWidgets.QComboBox(fileViewer)
        self.nodeSelector.setObjectName("nodeSelector")
        self.verticalLayout.addWidget(self.nodeSelector)
        self.fileSelector = QtWidgets.QComboBox(fileViewer)
        self.fileSelector.setObjectName("fileSelector")
        self.verticalLayout.addWidget(self.fileSelector)
        self.contentList = QtWidgets.QListWidget(fileViewer)
        self.contentList.setObjectName("contentList")
        self.verticalLayout.addWidget(self.contentList)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.loadButton = QtWidgets.QPushButton(fileViewer)
        self.loadButton.setObjectName("loadButton")
        self.horizontalLayout.addWidget(self.loadButton)
        self.saveButton = QtWidgets.QPushButton(fileViewer)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout.addWidget(self.saveButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(fileViewer)
        QtCore.QMetaObject.connectSlotsByName(fileViewer)

    def retranslateUi(self, fileViewer):
        _translate = QtCore.QCoreApplication.translate
        fileViewer.setWindowTitle(_translate("fileViewer", "Form"))
        self.label.setText(_translate("fileViewer", "File Viewer"))
        self.loadButton.setText(_translate("fileViewer", "Load"))
        self.saveButton.setText(_translate("fileViewer", "Save"))
