# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui\frameViewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frameViewer(object):
    def setupUi(self, frameViewer):
        frameViewer.setObjectName("frameViewer")
        frameViewer.resize(796, 504)
        self.verticalLayout = QtWidgets.QVBoxLayout(frameViewer)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widgetTitle = QtWidgets.QLabel(frameViewer)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.widgetTitle.setFont(font)
        self.widgetTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.widgetTitle.setObjectName("widgetTitle")
        self.verticalLayout.addWidget(self.widgetTitle)
        self.msgTable = QtWidgets.QTableWidget(frameViewer)
        self.msgTable.setStyleSheet("")
        self.msgTable.setObjectName("msgTable")
        self.msgTable.setColumnCount(0)
        self.msgTable.setRowCount(0)
        self.verticalLayout.addWidget(self.msgTable)

        self.retranslateUi(frameViewer)
        QtCore.QMetaObject.connectSlotsByName(frameViewer)

    def retranslateUi(self, frameViewer):
        _translate = QtCore.QCoreApplication.translate
        frameViewer.setWindowTitle(_translate("frameViewer", "Form"))
        self.widgetTitle.setText(_translate("frameViewer", "Frame Viewer"))
