# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui\logImport.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_logImport(object):
    def setupUi(self, logImport):
        logImport.setObjectName("logImport")
        logImport.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(logImport)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(logImport)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.fileSelectLabel = QtWidgets.QLabel(logImport)
        self.fileSelectLabel.setObjectName("fileSelectLabel")
        self.verticalLayout.addWidget(self.fileSelectLabel)
        self.fileButton = QtWidgets.QPushButton(logImport)
        self.fileButton.setObjectName("fileButton")
        self.verticalLayout.addWidget(self.fileButton)
        self.joinCheck = QtWidgets.QCheckBox(logImport)
        self.joinCheck.setObjectName("joinCheck")
        self.verticalLayout.addWidget(self.joinCheck)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.importButton = QtWidgets.QPushButton(logImport)
        self.importButton.setObjectName("importButton")
        self.verticalLayout.addWidget(self.importButton)
        self.label_2 = QtWidgets.QLabel(logImport)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)

        self.retranslateUi(logImport)
        QtCore.QMetaObject.connectSlotsByName(logImport)

    def retranslateUi(self, logImport):
        _translate = QtCore.QCoreApplication.translate
        logImport.setWindowTitle(_translate("logImport", "Log Import"))
        self.label.setText(_translate("logImport", "Log Import"))
        self.fileSelectLabel.setText(_translate("logImport", "Select a log file to import."))
        self.fileButton.setText(_translate("logImport", "Select File"))
        self.joinCheck.setText(_translate("logImport", "Is joining log file"))
        self.importButton.setText(_translate("logImport", "Import"))
        self.label_2.setText(_translate("logImport", "Warning: Importing will clear the current recorded data."))
