# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui\variable.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_variableDisplay(object):
    def setupUi(self, variableDisplay):
        variableDisplay.setObjectName("variableDisplay")
        variableDisplay.resize(159, 85)
        self.horizontalLayout = QtWidgets.QHBoxLayout(variableDisplay)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Name = QtWidgets.QLabel(variableDisplay)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Name.setFont(font)
        self.Name.setObjectName("Name")
        self.horizontalLayout.addWidget(self.Name)
        self.Value = QtWidgets.QLineEdit(variableDisplay)
        self.Value.setReadOnly(True)
        self.Value.setObjectName("Value")
        self.horizontalLayout.addWidget(self.Value)
        self.Units = QtWidgets.QLabel(variableDisplay)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Units.setFont(font)
        self.Units.setObjectName("Units")
        self.horizontalLayout.addWidget(self.Units)

        self.retranslateUi(variableDisplay)
        QtCore.QMetaObject.connectSlotsByName(variableDisplay)

    def retranslateUi(self, variableDisplay):
        _translate = QtCore.QCoreApplication.translate
        variableDisplay.setWindowTitle(_translate("variableDisplay", "Form"))
        self.Name.setText(_translate("variableDisplay", "Value"))
        self.Value.setPlaceholderText(_translate("variableDisplay", "Stale"))
        self.Units.setText(_translate("variableDisplay", "Units"))
