# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui\widgetDeleter.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widgetDelete(object):
    def setupUi(self, widgetDelete):
        widgetDelete.setObjectName("widgetDelete")
        widgetDelete.resize(400, 198)
        self.verticalLayout = QtWidgets.QVBoxLayout(widgetDelete)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(widgetDelete)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.widgetList = QtWidgets.QListWidget(widgetDelete)
        self.widgetList.setObjectName("widgetList")
        self.verticalLayout.addWidget(self.widgetList)
        self.selectBtn = QtWidgets.QPushButton(widgetDelete)
        self.selectBtn.setObjectName("selectBtn")
        self.verticalLayout.addWidget(self.selectBtn)

        self.retranslateUi(widgetDelete)
        QtCore.QMetaObject.connectSlotsByName(widgetDelete)

    def retranslateUi(self, widgetDelete):
        _translate = QtCore.QCoreApplication.translate
        widgetDelete.setWindowTitle(_translate("widgetDelete", "Delete Widget"))
        self.label.setText(_translate("widgetDelete", "Select display widget to remove."))
        self.selectBtn.setText(_translate("widgetDelete", "Select"))
